name = "notraceaudio-quota-worker"
main = "src/index.js"
compatibility_date = "2026-05-09"

[vars]
FREE_DAILY_LIMIT = "3"
# Comma separated list, example: "https://mydomain.com,https://mydomain.pages.dev"
ALLOWED_ORIGINS = "*"

[[kv_namespaces]]
binding = "QUOTA_KV"
id = "585010e6d12a4e5d8ee3d03f0fd80ea5"
preview_id = "3bf87a220d1d4de68d38d3cfeef1bb07"

[[d1_databases]]
binding = "DB"
database_name = "notraceaudio-quota"
database_id = "b4c171be-1b65-4755-9158-34f74369a5af"
